apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
spec:
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
    spec:
      containers:
      - name: node-exporter
        image: prom/node-exporter:latest
        args: 
          - --path.rootfs=/host/root
          - --path.sysfs=/host/sys
        ports:
        - containerPort: 9100
        volumeMounts:
          - name: host-root
            mountPath: /host/root
            readOnly: true
          - name: host-sys
            mountPath: /host/sys
            readOnly: true
      volumes:
        - name: host-root
          hostPath:
            path: /
        - name: host-sys
          hostPath:
            path: /sys
