apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-service-deployment
spec:
  selector:
    matchLabels:
      app: patient-service
  template:
    metadata:
      labels:
        app: patient-service
    spec:
      replicas: 1
      containers:
      - name: patient-service
        image: khaled97dc/patient-service-app:1.0
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 4000
